// constants/questions.ts
import { CATEGORIES } from './categories';

export const QUESTIONS = {
  [CATEGORIES.ICEBREAKER]: [
    { id: 1, text: "If you could eat only one cuisine for the rest of your life, which do you pick, and what's the one dish that seals it?" },
    { id: 2, text: "What's something you got totally obsessed with for a month and then completely forgot about?" },
    { id: 3, text: 'Do you have a go-to karaoke song? What does that song say about you?' },
    { id: 4, text: "What's the most random skill you have that would make zero sense on a résumé?" },
    { id: 5, text: 'If you had to describe your energy before coffee vs. after coffee, what two animals are you?' },
    { id: 6, text: "What's a movie or show everyone loves that you just cannot get into?" },
    { id: 7, text: "What's your version of the perfect lazy Sunday?" },
    { id: 8, text: "What's the last thing you got genuinely excited about telling someone?" },
    { id: 9, text: "Are you a 'figure it out as you go' person or a 'research for three hours first' person?" },
    { id: 10, text: "What's a purchase you made that you thought was impulsive but turned out to be the best decision?" },
    { id: 11, text: 'What did you want to be when you were nine? How far off is that from now?' },
    { id: 12, text: "What's something that's on your playlist that would surprise people who just met you?" },
    { id: 13, text: "Do you collect anything? Even informally, even just in your phone's camera roll?" },
    { id: 14, text: "What's your unpopular food opinion that you'll defend completely?" },
    { id: 15, text: 'If you had to describe your current apartment or room in three words, what are they?' },
    { id: 16, text: "What's a place in this city you keep meaning to go to but still haven't?" },
    { id: 17, text: "What's the last thing that made you laugh so hard you couldn't speak?" },
    { id: 18, text: "Morning routine: are you a 'up and going immediately' person or 'need thirty minutes of just lying there' person?" },
    { id: 19, text: "What's something you'd bring to a potluck to genuinely impress people?" },
    { id: 20, text: "What's a childhood TV show that still holds up perfectly in your opinion?" },
    { id: 21, text: "Do you have a 'third place', somewhere that isn't home or work where you actually feel at ease?" },
    { id: 22, text: "What's your 'if I'm sad I put this on' movie?" },
    { id: 23, text: "What's something you're weirdly good at that almost never comes up?" },
    { id: 24, text: "What's the best thing you've made with your own hands, cooked, built, created, anything?" },
    { id: 25, text: "What's a small habit or ritual that your day genuinely feels off without?" },
    { id: 26, text: 'If you had to teach a one-hour class on something right now, no prep, what would it be?' },
    { id: 27, text: "What's a trip, near or far, that changed how you thought about something?" },
    { id: 28, text: "Do you tend to remember dreams? What's a weird recurring one, if any?" },
    { id: 29, text: "What's a book, podcast, or article you've sent to more than one person?" },
    { id: 30, text: "What's something you thought you'd hate and then totally fell for?" },
  ],
  [CATEGORIES.DEEP]: [
    { id: 1, text: "Tell me about a moment where you surprised yourself: did something you didn't know you were capable of." },
    { id: 2, text: "What's a belief you held for years that you eventually had to let go of?" },
    { id: 3, text: 'What does a really good friendship look like to you? What makes it different from an average one?' },
    { id: 4, text: "When do you feel most like yourself, the most 'you'?" },
    { id: 5, text: "Is there something you've never quite articulated out loud that you've been slowly figuring out about yourself?" },
    { id: 6, text: "What's a chapter of your life that was hard at the time but you're now grateful for?" },
    { id: 7, text: 'What kind of environment do you need to actually recharge, not just rest, but genuinely feel restored?' },
    { id: 8, text: "Who's someone who shaped who you are in a way they probably don't even know?" },
    { id: 9, text: "What do you wish people understood about you that doesn't come through right away?" },
    { id: 10, text: "What's something you've changed your mind about in the last few years?" },
    { id: 11, text: 'Is there a version of yourself from five or ten years ago that would be surprised by who you are now?' },
    { id: 12, text: "What's something you've worked hard for that actually meant something when you got it?" },
    { id: 13, text: 'How do you know when you trust someone?' },
    { id: 14, text: "What's a value you genuinely live by versus one you just think you should live by?" },
    { id: 15, text: "What does 'home' feel like to you: is it a place, a person, a feeling?" },
    { id: 16, text: "What's a fear that's actually held you back in some way?" },
    { id: 17, text: "What's one thing you need a partner to truly understand about you?" },
    { id: 18, text: "What do you think you're still figuring out about how to love people well?" },
    { id: 19, text: "What's something you've done out of obligation that you're glad you did anyway?" },
    { id: 20, text: 'When was the last time you cried, and was it about what it seemed to be about?' },
    { id: 21, text: "What do you want more of in your life right now that you haven't fully made room for?" },
    { id: 22, text: "What's a quality you're proud of that took you a long time to develop?" },
    { id: 23, text: 'How do you handle it when you and someone you care about want very different things?' },
    { id: 24, text: "What's a version of success you've quietly let go of, and do you miss it?" },
    { id: 25, text: "What makes you feel like you're not enough? And do you believe it?" },
    { id: 26, text: "What's your relationship with asking for help?" },
    { id: 27, text: "What's something you've never quite gotten over, not in a bad way, just in a 'it still matters' way?" },
    { id: 28, text: "What lights you up in a way that's hard to explain to people who don't share it?" },
    { id: 29, text: 'What are you learning about yourself right now?' },
    { id: 30, text: "If the people who love you most described you, what would they say that you'd disagree with?" },
  ],
  [CATEGORIES.FUTURE]: [
    { id: 1, text: 'If you could design your life five years from now with total freedom, what does an average Tuesday look like?' },
    { id: 2, text: "Is there something you've been putting off starting that you actually really want to do?" },
    { id: 3, text: "What's a version of your life you could see being really happy in that might surprise people?" },
    { id: 4, text: 'Is there a city or country that keeps coming back to you, somewhere you think about more than makes sense?' },
    { id: 5, text: "What would you want to be really good at by the time you're old?" },
    { id: 6, text: "Is there something you want to build, a project, a business, a creative thing, that you haven't started yet?" },
    { id: 7, text: 'What does the relationship you want eventually feel like, day-to-day?' },
    { id: 8, text: "What's something you want to experience at least once in your life, no matter what?" },
    { id: 9, text: 'Do you want to live the same kind of life your parents lived, or something completely different?' },
    { id: 10, text: "What's a skill or language or craft you'd learn if time was genuinely no obstacle?" },
    { id: 11, text: 'Is there a cause or idea that you think matters deeply and want to spend more of your life on?' },
    { id: 12, text: 'What does retirement mean to you, or is that even a concept you think about?' },
    { id: 13, text: "What's a tradition you'd want to carry forward, or a new one you'd want to create?" },
    { id: 14, text: "Do you have a vision of what kind of parent you'd be, want to be, or not want to be?" },
    { id: 15, text: "What's a risk you want to take but haven't quite worked up to yet?" },
    { id: 16, text: "What's something you hope to stop caring about as you get older?" },
    { id: 17, text: 'If you could live somewhere very different for a year, and I mean really different, where would it be?' },
    { id: 18, text: 'What kind of impact do you hope to have had on the people close to you, by the end of things?' },
    { id: 19, text: "What's a goal that you keep setting and haven't hit yet, and why do you think that is?" },
    { id: 20, text: "Is there something you used to dream about that you've quietly let go of? Any part of you miss it?" },
    { id: 21, text: "If money genuinely weren't a factor, what would you spend most of your time doing?" },
    { id: 22, text: "What does your ideal creative outlet or project look like, even if it's just a fantasy for now?" },
    { id: 23, text: "What's something you want to get better at in how you show up for the people you love?" },
    { id: 24, text: "What's a simple life goal that doesn't sound impressive but actually matters a lot to you?" },
    { id: 25, text: 'Is there something in your life you want to do more intentionally going forward?' },
    { id: 26, text: 'If you wrote a letter to yourself to open in twenty years, what would you most want to have done by then?' },
    { id: 27, text: "What kind of friendships do you want in your life that you don't quite have yet?" },
    { id: 28, text: 'If you could spend one year doing exactly what you love with no consequences: what does that look like?' },
    { id: 29, text: "What's a lifestyle change you've been circling but haven't committed to?" },
    { id: 30, text: "What's one thing you hope to get braver about?" },
  ],
  [CATEGORIES.FUNNY]: [
    { id: 1, text: "What's the most elaborate lie you've told to get out of something, and did it work?" },
    { id: 2, text: "What's a song you sing at full volume in the car that you would be mortified if anyone heard?" },
    { id: 3, text: "What's the most unhinged food combination you eat that you'll actually defend?" },
    { id: 4, text: "What's the weirdest thing you've ever Googled at 2am?" },
    { id: 5, text: "What's something you've done that you genuinely cannot explain?" },
    { id: 6, text: "What's the most dramatic thing you've ever done over something totally trivial?" },
    { id: 7, text: "What's a conspiracy theory you half-believe just because it's more fun than the truth?" },
    { id: 8, text: "What's the worst gift you've ever received, and how did you react?" },
    { id: 9, text: 'If your pet (real or hypothetical) could talk, what would be their main complaints about you?' },
    { id: 10, text: "What's a phrase or word you use constantly that other people find annoying?" },
    { id: 11, text: "What's a movie you've pretended to have seen that you definitely haven't?" },
    { id: 12, text: "What's the most 'this is fine' situation you've ever just calmly walked through?" },
    { id: 13, text: "What's a phase you went through that you've fully erased from your public identity?" },
    { id: 14, text: "What's the most ridiculous argument you've gotten into, and did you win?" },
    { id: 15, text: "What's a skill you were confident you had until you tried it in front of someone?" },
    { id: 16, text: "What fictional character are you exactly like in ways you wish you weren't?" },
    { id: 17, text: "What's a thing you do when no one is watching that you wouldn't want on camera?" },
    { id: 18, text: "What's the most 'main character' moment you've ever had in public?" },
    { id: 19, text: "What's a nickname you've had that you either love or deeply resent?" },
    { id: 20, text: "What's an activity you somehow convinced yourself you were good at for way too long?" },
    { id: 21, text: "What's the worst date story you have? (Other than this one, of course.)" },
    { id: 22, text: "What's your most irrational hill to die on?" },
    { id: 23, text: "What's something you've dramatically quit and then quietly gone back to?" },
    { id: 24, text: 'If someone made a documentary about your life, what would the title and tone be?' },
    { id: 25, text: "What's the most embarrassing thing that's ever autocorrected at the worst possible moment?" },
    { id: 26, text: "What's a weird dream you've had that genuinely made you question yourself?" },
    { id: 27, text: "What's a tiny thing that ruins your day more than it has any right to?" },
    { id: 28, text: "What's your 'I'm fine, this is totally normal' face look like, and when do you use it?" },
    { id: 29, text: "What's the most cursed family tradition or story that you've kind of accepted as normal?" },
    { id: 30, text: "What's the most confidently wrong you've ever been about something?" },
  ],
  [CATEGORIES.ROMANTIC]: [
    { id: 1, text: 'What does it feel like when you actually like someone, like, what changes in you?' },
    { id: 2, text: "What's something a person can do early on that immediately makes you more interested?" },
    { id: 3, text: "Is there a moment from a relationship, real or fictional, that's kind of set the bar for what you want?" },
    { id: 4, text: 'Do you fall for people slowly or does it tend to happen all at once?' },
    { id: 5, text: "What's the thing someone does that makes you feel the most taken care of?" },
    { id: 6, text: "What's your favorite way to spend time with someone you really like: what does that look like?" },
    { id: 7, text: "Do you tend to say what you're feeling or does it come out sideways?" },
    { id: 8, text: "What's something a partner can do that makes you feel genuinely seen?" },
    { id: 9, text: "What does real chemistry feel like to you: how do you know it's there?" },
    { id: 10, text: 'Are you better at grand gestures or quiet, consistent ones?' },
    { id: 11, text: "What's a small thing someone did for you that you've never quite forgotten?" },
    { id: 12, text: 'Is there a type of moment, first coffee, late night talking, a long walk, that you love most in early dating?' },
    { id: 13, text: 'What makes you actually want to make an effort with someone?' },
    { id: 14, text: "What's something you find attractive that's not the obvious stuff?" },
    { id: 15, text: 'Are you the kind of person who needs space to fall for someone, or does closeness do it?' },
    { id: 16, text: "What's your favorite thing to do with someone you're completely comfortable with?" },
    { id: 17, text: "What's a quality you notice in someone that makes you think 'I want to know more about this person'?" },
    { id: 18, text: 'What does feeling safe with someone feel like to you?' },
    { id: 19, text: 'Have you ever fallen for someone at a completely unexpected time or place?' },
    { id: 20, text: "What's the most romantic thing that's actually worked on you?" },
    { id: 21, text: "Do you have a 'type'? And do you actually end up with your type?" },
    { id: 22, text: 'What makes a first date go from good to really good?' },
    { id: 23, text: "What's something you do when you like someone that you're not sure they notice?" },
    { id: 24, text: 'What does it feel like when someone genuinely makes you laugh, like properly laugh?' },
    { id: 25, text: 'When do you feel most attractive?' },
    { id: 26, text: "What's something that matters a lot to you in a relationship that people might not expect?" },
    { id: 27, text: "What's the best compliment someone's ever given you that had nothing to do with how you look?" },
    { id: 28, text: "What makes you feel like yourself around someone you're dating?" },
    { id: 29, text: "Is there a version of a relationship you used to want that you've grown out of?" },
    { id: 30, text: "What's something you hope someone figures out about you without you having to say it?" },
  ],
  [CATEGORIES.WILD]: [
    { id: 1, text: "What's the most spontaneous thing you've ever done, the one that surprised even you?" },
    { id: 2, text: "What's a rule you think is genuinely worth breaking?" },
    { id: 3, text: 'Have you ever completely reinvented yourself? What was the before and after?' },
    { id: 4, text: "What's the riskiest bet you've ever taken, on a person, a job, a city, anything?" },
    { id: 5, text: "What's something you've done that felt terrifying in the moment and legendary in retrospect?" },
    { id: 6, text: "Have you ever told someone how you felt when you had absolutely no idea how they'd respond?" },
    { id: 7, text: "What's your most chaotic era, and what caused it?" },
    { id: 8, text: "What's a version of yourself that only certain people have seen?" },
    { id: 9, text: "What's something you've wanted to do but talked yourself out of, and do you regret it?" },
    { id: 10, text: "What's the most morally gray thing you've done that you'd still defend?" },
    { id: 11, text: "What's your biggest guilty pleasure that you've stopped apologizing for?" },
    { id: 12, text: 'Have you ever done something completely out of character and loved it?' },
    { id: 13, text: "What's a secret you've kept for so long it's become part of you?" },
    { id: 14, text: "What's something that's on your 'never again' list, and why?" },
    { id: 15, text: "What's the most honest you've ever been with someone? Did it go well?" },
    { id: 16, text: "Is there something you've done that people who know you now would never believe?" },
    { id: 17, text: "What's something you find attractive that you've never quite admitted out loud?" },
    { id: 18, text: "What's a fantasy you have, about life, a place, a scenario, that's a little embarrassing to say out loud?" },
    { id: 19, text: "What's a moment where you thought 'I can't believe I just did that' in the best way?" },
    { id: 20, text: "What's the boldest thing you've ever done for someone you liked?" },
    { id: 21, text: 'Is there something you want to do right now but would normally talk yourself out of?' },
    { id: 22, text: "What's an experience you'd repeat in a heartbeat even knowing how it ended?" },
    { id: 23, text: "What's your biggest turn-on that's not the obvious stuff?" },
    { id: 24, text: "What's the wildest thing you'd do on a second date if you felt completely comfortable?" },
    { id: 25, text: 'Have you ever completely misread a situation with someone and been delightfully wrong?' },
    { id: 26, text: "What's something about you that people are usually surprised to find out?" },
    { id: 27, text: "What's a craving you have right now, for an experience, a feeling, anything?" },
    { id: 28, text: "What's the most honest version of what you're actually looking for right now?" },
    { id: 29, text: 'Have you ever done something just to see what would happen?' },
    { id: 30, text: "What's a line you've crossed that you'd cross again?" },
  ],
};
