// constants/questions.ts
import { CATEGORIES } from './categories';

export const QUESTIONS = {
  [CATEGORIES.DEEP]: [
    { id: 1, text: "What's a belief you hold that you're willing to have challenged?" },
    { id: 2, text: "What's something you're passionate about learning right now?" },
    { id: 3, text: "What's a personal value you prioritize most in your life?" },
    { id: 4, text: "What's a moment in your life that significantly changed your perspective?" },
    { id: 5, text: "What's a quality you admire most in other people?" },
    { id: 6, text: "What's something you're working on improving about yourself?" },
    { id: 7, text: "If you could have any superpower related to empathy, what would it be?" },
    { id: 8, text: "What's a lesson you've learned the hard way?" },
    { id: 9, text: "What's a dream you have that you haven't told many people about?" },
    { id: 10, text: "What kind of legacy do you hope to leave behind?" },
    { id: 11, text: "What does vulnerability mean to you?" },
    { id: 12, text: "What's something you're grateful for today?" },
    { id: 13, text: "What's a fear you're trying to overcome?" },
    { id: 14, text: "How do you define success in life?" },
    { id: 15, text: "What's a book, movie, or song that deeply resonated with you? Why?" },
    { id: 16, text: "What's a cause you'd like to support or get involved with?" },
    { id: 17, text: "What's your preferred way to receive emotional support?" },
    { id: 18, text: "What's a time you felt truly understood by someone?" },
    { id: 19, text: "How do you handle conflict or disagreement?" },
    { id: 20, text: "What's your biggest non-negotiable in a relationship?" },
    { id: 21, text: "What does \"authenticity\" mean to you?" },
    { id: 22, text: "What's a personal boundary you're firm about?" },
    { id: 23, text: "What's something you've learned about yourself from past relationships?" },
    { id: 24, text: "What's a time you felt most alive and present?" },
    { id: 25, text: "How do you typically recharge after a stressful day?" },
    { id: 26, text: "What's a mistake you've made that you learned a lot from?" },
    { id: 27, text: "What's a relationship (familial, platonic, or romantic) that has shaped you?" },
    { id: 28, text: "What's your philosophy on forgiveness?" },
    { id: 29, text: "What's a difficult decision you've had to make, and how did you approach it?" },
    { id: 30, text: "What's your biggest strength in relationships?" },
  ],
  [CATEGORIES.ICEBREAKER]: [
    { id: 1, text: "What's your favorite way to spend a weekend?" },
    { id: 2, text: "What's a hobby you enjoy or would like to try?" },
    { id: 3, text: "What's your go-to comfort food?" },
    { id: 4, text: "What's a place you've always dreamed of traveling to?" },
    { id: 5, text: "What's your favorite type of music or artist?" },
    { id: 6, text: "What's a TV show or movie you can watch over and over?" },
    { id: 7, text: "Do you prefer coffee or tea? How do you take it?" },
    { id: 8, text: "Are you a morning person or a night owl?" },
    { id: 9, text: "What's your favorite season and why?" },
    { id: 10, text: "What's a skill you'd love to learn?" },
    { id: 11, text: "What's your favorite animal?" },
    { id: 12, text: "Do you prefer city life, country life, or something in between?" },
    { id: 13, text: "What's a board game or card game you enjoy?" },
    { id: 14, text: "What's your favorite type of cuisine?" },
    { id: 15, text: "Do you have any pets? If so, tell me about them." },
    { id: 16, text: "What's a unique talent or skill you possess?" },
    { id: 17, text: "What's your favorite way to exercise or stay active?" },
    { id: 18, text: "What's a subject in school you enjoyed or excelled at?" },
    { id: 19, text: "What's your favorite holiday and why?" },
    { id: 20, text: "Do you prefer indoor or outdoor activities?" },
    { id: 21, text: "What's a simple pleasure that always makes you happy?" },
    { id: 22, text: "What's your favorite type of weather?" },
    { id: 23, text: "What's a childhood memory that makes you smile?" },
    { id: 24, text: "What's your preferred way to stay organized?" },
    { id: 25, text: "What's your favorite scent or smell?" },
    { id: 26, text: "Do you enjoy cooking or baking?" },
    { id: 27, text: "What's a sport you enjoy watching or playing?" },
    { id: 28, text: "What's a type of art or creative expression you appreciate?" },
    { id: 29, text: "What's your favorite kind of dessert?" },
    { id: 30, text: "What's a recent accomplishment you're proud of?" },
  ],
  [CATEGORIES.FUTURE]: [
    { id: 1, text: "What's a goal you're currently working towards?" },
    { id: 2, text: "Where do you see yourself in five years (in a broad sense)?" },
    { id: 3, text: "What's a skill you'd like to develop in the future?" },
    { id: 4, text: "What's a travel experience you'd like to have someday?" },
    { id: 5, text: "What's a personal project you'd like to undertake?" },
    { id: 6, text: "What's a change you'd like to see in the world?" },
    { id: 7, text: "What's a type of home you'd love to live in someday?" },
    { id: 8, text: "What's a career path you've considered or are curious about?" },
    { id: 9, text: "What's a way you'd like to grow as a person in the future?" },
    { id: 10, text: "What's an adventure you'd like to go on?" },
    { id: 11, text: "What's a creative project you'd like to try?" },
    { id: 12, text: "What kind of impact do you hope to make on others' lives?" },
    { id: 13, text: "What's a new experience you'd like to have?" },
    { id: 14, text: "What's a long-term goal you have, big or small?" },
    { id: 15, text: "What's a way you'd like to contribute to your community?" },
    { id: 16, text: "What's a hobby you'd like to dedicate more time to?" },
    { id: 17, text: "What's a type of learning you'd like to pursue?" },
    { id: 18, text: "What's a personal challenge you'd like to take on?" },
    { id: 19, text: "What's a relationship you'd like to nurture or develop?" },
    { id: 20, text: "What does your ideal retirement look like (even if it's far off)?" },
    { id: 21, text: "What's a technology you're excited about for the future?" },
    { id: 22, text: "What's a way you'd like to give back to others?" },
    { id: 23, text: "What's a personal tradition you'd like to start?" },
    { id: 24, text: "What's a life lesson you hope to pass on to future generations?" },
    { id: 25, text: "What's a positive change you'd like to make in your own life?" },
    { id: 26, text: "What's a dream you have for your family (current or future)?" },
    { id: 27, text: "What's a way you'd like to make your daily life more fulfilling?" },
    { id: 28, text: "What's a legacy you'd like to build, even in a small way?" },
    { id: 29, text: "What's a skill you'd like to master?" },
    { id: 30, text: "What's a \"bucket list\" item you're determined to accomplish?" },
  ],
  [CATEGORIES.FUNNY]: [
    { id: 1, text: "What's the most embarrassing song you secretly love?" },
    { id: 2, text: "What's the weirdest food combination you enjoy?" },
    { id: 3, text: "What's a silly fear you have?" },
    { id: 4, text: "What's the most ridiculous thing you've ever done for a dare?" },
    { id: 5, text: "What's a funny childhood memory that still makes you laugh?" },
    { id: 6, text: "What's your worst fashion mistake?" },
    { id: 7, text: "If you could have any animal as a tiny, pocket-sized pet, what would it be?" },
    { id: 8, text: "What's the most embarrassing thing that's happened to you on a date?" },
    { id: 9, text: "What's a funny joke you know?" },
    { id: 10, text: "What's a movie or TV show you find unintentionally hilarious?" },
    { id: 11, text: "What's the most absurd talent you have?" },
    { id: 12, text: "What's a funny mispronunciation you've had or heard?" },
    { id: 13, text: "If you could have a ridiculous superpower, what would it be?" },
    { id: 14, text: "What's the weirdest dream you've ever had?" },
    { id: 15, text: "What's a funny autocorrect fail you've experienced?" },
    { id: 16, text: "What's your go-to dance move?" },
    { id: 17, text: "What's a funny impression you can do (even if it's bad)?" },
    { id: 18, text: "What's a product you've seen advertised that made you laugh?" },
    { id: 19, text: "What's the silliest thing you've ever argued about?" },
    { id: 20, text: "What's a funny nickname you've had?" },
    { id: 21, text: "What's a situation where you laughed at the completely wrong time?" },
    { id: 22, text: "What's the most ridiculous thing you believed as a child?" },
    { id: 23, text: "What's a funny story about a pet you've had (or encountered)?" },
    { id: 24, text: "What's the worst pickup line you've ever heard or used?" },
    { id: 25, text: "What's a funny thing you've done while sleepwalking (or heard about someone else doing)?"},
    { id: 26, text: "What's a meme or internet trend that you find hilarious?" },
    { id: 27, text: "What's a funny misunderstanding you've had?" },
    { id: 28, text: "What's the most ridiculous item of clothing you own?" },
    { id: 29, text: "What's a funny word or phrase you like to use?" },
    { id: 30, text: "What's the most embarrassing thing you've Googled recently?" },
  ],
  [CATEGORIES.ROMANTIC]: [
    { id: 1, text: "What's your idea of a perfect date?" },
    { id: 2, text: "What's a quality you find attractive in a partner?" },
    { id: 3, text: "What's your love language (how do you show and receive affection)?" },
    { id: 4, text: "What's your favorite romantic movie or song?" },
    { id: 5, text: "Do you believe in love at first sight?" },
    { id: 6, text: "What's a gesture that you find particularly romantic?" },
    { id: 7, text: "What's your favorite way to be shown affection?" },
    { id: 8, text: "What's a compliment that always makes you smile?" },
    { id: 9, text: "What's your idea of a romantic getaway?" },
    { id: 10, text: "What's something you find endearing in others?" },
    { id: 11, text: "What's a romantic gesture you've done for someone else?" },
    { id: 12, text: "What's a feeling you enjoy experiencing in a relationship?" },
    { id: 13, text: "What's your favorite thing about being in a relationship (or the idea of it)?" },
    { id: 14, text: "What's a way you like to make your partner feel special?" },
    { id: 15, text: "What's a quality that makes you feel connected to someone?" },
    { id: 16, text: "Do you prefer grand romantic gestures or small, everyday acts of love?" },
    { id: 17, text: "What's a romantic setting you find appealing (e.g., beach, fireplace)?" },
    { id: 18, text: "What's a way you like to express your feelings to someone you care about?" },
    { id: 19, text: "What's a relationship \"goal\" you have (e.g., slow dancing in the kitchen)?" },
    { id: 20, text: "What's something you find attractive about me? (Use with discretion!)" },
    { id: 21, text: "What's a memory of a romantic moment (real or fictional) that you cherish?" },
    { id: 22, text: "What's a characteristic you find charming?" },
    { id: 23, text: "What's a way you like to be surprised by a partner?" },
    { id: 24, text: "What's a simple pleasure you'd enjoy sharing with a partner?" },
    { id: 25, text: "What's a quality that makes you feel safe and secure with someone?" },
    { id: 26, text: "What's your favorite type of physical affection (e.g., hugs, holding hands)?" },
    { id: 27, text: "What's a romantic activity you'd like to try?" },
    { id: 28, text: "What's a way you show someone you're thinking of them?" },
    { id: 29, text: "What's a feeling you associate with falling in love?" },
    { id: 30, text: "What do you think is the key to a successful relationship?" },
  ],
  [CATEGORIES.WILD]: [
    { id: 1, text: "What's the most spontaneous thing you've ever done?" },
    { id: 2, text: "Have you ever gone skinny dipping?  If not, would you?" },
    { id: 3, text: "What's the riskiest thing you've ever done?" },
    { id: 4, text: "What's a rule you've broken (and gotten away with)?"},
    { id: 5, text: "If you could get away with anything, what would you do?" },
    { id: 6, text: "What's your biggest guilty pleasure?" },
    { id: 7, text: "Have you ever had a 'one-night stand'?  Would you?" },
    { id: 8, text: "What's something you've done that you'd never tell your parents?" },
    { id: 9, text: "What's the most adventurous thing you've eaten?" },
    { id: 10, text: "Have you ever been arrested (or come close)? What for?" },
    { id: 11, text: "What's a fantasy you've had that you'd be embarrassed to admit?" },
    { id: 12, text: "What's the most daring thing you'd be willing to try on a dare?" },
    { id: 13, text: "If you could travel anywhere in the world right now, where would you go and why?" },
    { id: 14, text: "Have you ever lied to get out of trouble? What was the lie?" },
    { id: 15, text: "What's something you're secretly a little rebellious about?" },
    { id: 16, text: "What's the craziest thing you've done while drunk (or heard about someone else doing)?" },
    { id: 17, text: "If you could swap lives with someone for a day, who would it be and why?" },
    { id: 18, text: "What's a public place you've thought about having sex in?" },
    { id: 19, text: "What's your biggest turn-on?" },
    { id: 20, text: "What's your biggest turn-off?" },
    { id: 21, text: "Have you ever had a crush on a friend's partner?" },
    { id: 22, text: "What's a secret you've kept from a significant other?" },
    { id: 23, text: "What's the most embarrassing thing you've ever searched for online?" },
    { id: 24, text: "Have you ever sent a nude photo?  Would you?" },
    { id: 25, text: "What's something you'd only do if you knew you wouldn't get caught?" },
    { id: 26, text: "Have you ever cheated on someone (in any context, not just romantic)?" },
    { id: 27, text: "What's your opinion on open relationships?" },
    { id: 28, text: "What's a sexual experience you're curious to try?" },
    { id: 29, text: "What's something you find attractive that others might find strange?" },
    { id: 30, text: "Have you ever been caught doing something you shouldn't have been?" },
  ],
};